language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install coveralls
  - sh -c 'cd conpaas-director' && python setup.py install
script: 
  - sh -c 'cd conpaas-director' && coverage run --source=cpsdirector test.py
after_success: 
  - coveralls
notifications:
  email:
    - ema@linux.it
