language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install coveralls
  - python conpaas-director/setup.py install
script: 
  - coverage run --source=cpsdirector conpaas-director/test.py
after_success: 
  - coveralls
notifications:
  email:
    - ema@linux.it
