env:
  global:
    - REPO="ConPaaS-team/conpaas"
    - CI_HOME=`pwd`/$REPO
language: python
python:
  - 2.7
install:
  - sudo apt-get install python-numpy
  - pip install coveralls flask-sqlalchemy apache-libcloud netaddr mock cheetah pep8 pylint numpy pandas scipy
  - pip install statsmodels
script: 
  - ./travis.sh
after_success: 
  - coveralls
notifications:
  email:
    - yann.radenac@inria.fr
  on_success: always
  on_failure: always
