env:
  global:
    - REPO="ema/conpaas"
    - CI_HOME=`pwd`/$REPO
language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install coveralls
script: 
  - ./travis.sh
after_success: 
  - coveralls
notifications:
  email:
    - ema@linux.it
