#!/bin/bash

# setup and run local agent
tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
export PYTHONPATH=/root/ConPaaSWeb/src/
export LD_LIBRARY_PATH=/conpaas/lib
export PATH=/conpaas/bin:/conpaas/sbin:$PATH

python /root/ConPaaSWeb/src/conpaas/web/agent/server.py 1>/root/agent.out 2>/root/agent.err &
agent_pid=$!
echo $agent_pid > /root/agent.pid
