#!/bin/bash

# setup and run local agent
tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
cp /root/ConPaaSWeb/etc/nginx-proxy.tmpl /etc/cpsagent.web/nginx-proxy.tmpl
cp /root/ConPaaSWeb/etc/nginx-static.tmpl /etc/cpsagent.web/nginx-static.tmpl
cp /root/ConPaaSWeb/etc/fpm.tmpl /etc/cpsagent.web/fpm.tmpl
cp /root/ConPaaSWeb/etc/tomcat-server-xml.tmpl /etc/cpsagent.web/tomcat-server-xml.tmpl
cp /root/ConPaaSWeb/etc/tomcat-catalina.policy /etc/cpsagent.web/tomcat-catalina.policy

export PYTHONPATH=/root/ConPaaSWeb/src/:/root/ConPaaSWeb/contrib

/root/ConPaaSWeb/sbin/cpsagent.web -c /root/config.cfg 1>/root/agent.out 2>/root/agent.err &
agent_pid=$!
echo $agent_pid > /root/agent.pid
