#!/bin/bash
# Copyright (C) 2010-2011 Contrail consortium.
# 
# This file is part of ConPaaS, an integrated runtime environment 
# for elastic cloud applications.
# 
# ConPaaS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ConPaaS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ConPaaS.  If not, see <http://www.gnu.org/licenses/>.

wget -P /root/ $SOURCE/ConPaaSWeb.tar.gz
wget -P /root/ $SOURCE/agent-start
wget -P /root/ $SOURCE/agent-stop

chmod 755 /root/agent-start
chmod 755 /root/agent-stop

cat <<EOF > /root/config.cfg
[nginx]
NGINX = /usr/sbin/nginx

[php]
PHP_FPM = /usr/sbin/php-fpm

[tomcat]
TOMCAT_INSTANCE_CREATE = /usr/bin/tomcat6-instance-create
TOMCAT_STARTUP = /usr/share/tomcat6/bin/startup.sh

[agent]
ROOT = 
LOG_FILE = %(ROOT)s/var/log/cpsagent.web.log
ETC = %(ROOT)s/etc/cpsagent.web/
VAR_TMP = %(ROOT)s/var/tmp/cpsagent.web/
VAR_CACHE = %(ROOT)s/var/cache/cpsagent.web/
VAR_RUN = %(ROOT)s/var/run/cpsagent.web/
IP_WHITE_LIST = $MANAGER_IP
EOF


/root/agent-start
