#!/bin/bash

tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
export PYTHONPATH=/root/ConPaaSWeb/src/:/root/ConPaaSWeb/contrib/

/etc/init.d/memcached start
/usr/local/bin/scalarisctl -d -f -s start

/root/ConPaaSWeb/sbin/cpsmanager.web -p 80 -c /root/config.cfg -s $PUBLIC_IP 1>/root/manager.out 2>/root/manager.err &
manager_pid=$!
echo $manager_pid > /root/manager.pid
