#!/bin/bash

VERSION="0.1"
PACKAGE="/usr/lib/python2.6/site-packages/conpaassql_server-${VERSION}-py2.6.egg"
EXEC="conpaas/mysql/server/manager/server.py"
CONF="/etc/contrail/conpaas/conpaas-mysql-manager.cnf"
OUT_BASE="/var/log/"
OUT_ERR="${OUT_BASE}/conpaas-mysql.err"
OUT_STD="${OUT_BASE}/conpaas-mysql.out"

EXPECTED_ARGS=2
E_BADARGS=65
if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` [IP of external interface] [listening port]" 
  exit $E_BADARGS
fi

IP=${1}
PORT=${2}

PYTHONPATH=${PACKAGE} python ${PACKAGE}/${EXEC} ${IP} ${PORT} -c ${CONF} 1> ${OUT_STD} 2> ${OUT_ERR}