#!/bin/bash

VERSION="0.1"
PACKAGE="/usr/lib/python2.6/site-packages/conpaassql_server-${VERSION}-py2.6.egg"
EXEC="conpaas/mysql/client/manager_client.py"
OUT_BASE="/var/log/"
OUT_ERR="${OUT_BASE}/conpaas-mysql-client.err"
OUT_STD="${OUT_BASE}/conpaas-mysql-client.out"

PYTHONPATH=${PACKAGE} python ${PACKAGE}/${EXEC} $* &