#!/bin/bash

/etc/init.d/memcached start
/usr/bin/scalarisctl -d -f -s start

# Enable GIT-based code uploads
. $CPS_HOME/scripts/manager/default-git-deploy-hook 

$CPS_HOME/sbin/manager/default-cpsmanager -c $ROOT_DIR/config.cfg 1>$ROOT_DIR/manager.out 2>$ROOT_DIR/manager.err &
manager_pid=$!
echo $manager_pid > $ROOT_DIR/manager.pid
