#!/bin/bash

export HOME=$ROOT_DIR
/usr/bin/scalarisctl -d -f -s start

# $CPS_HOME/sbin/manager/default-cpsmanager -c $ROOT_DIR/config.cfg 1>$ROOT_DIR/manager.out 2>$ROOT_DIR/manager.err &
# manager_pid=$!
# echo $manager_pid > $ROOT_DIR/manager.pid
