#!/bin/bash

# This script is part of the contextualization file. It 
# starts a python script that parses the given arguments
# and starts the manager server, which in turn will start
# the manager service. 

# This file is the default manager-start file. It can be
# customized as needed by the sevice.  

# Make sure that java will choose ipv4 over ipv6
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

$CPS_HOME/sbin/manager/taskfarm-cpsmanager -c $ROOT_DIR/config.cfg -a $IP_PUBLIC -s $CERT_DIR 1>$ROOT_DIR/manager.out 2>$ROOT_DIR/manager.err &
manager_pid=$!
echo $manager_pid > $ROOT_DIR/manager.pid
