#!/bin/bash
# Copyright (C) 2010-2011 Contrail consortium.
# 
# This file is part of ConPaaS, an integrated runtime environment 
# for elastic cloud applications.
# 
# ConPaaS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ConPaaS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ConPaaS.  If not, see <http://www.gnu.org/licenses/>.

# setup and run local agent
tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
cp /root/ConPaaSWeb/etc/nginx-proxy.tmpl /etc/cpsagent.web/nginx-proxy.tmpl
cp /root/ConPaaSWeb/etc/nginx-static.tmpl /etc/cpsagent.web/nginx-static.tmpl
cp /root/ConPaaSWeb/etc/fpm.tmpl /etc/cpsagent.web/fpm.tmpl
cp /root/ConPaaSWeb/etc/tomcat-server-xml.tmpl /etc/cpsagent.web/tomcat-server-xml.tmpl
cp /root/ConPaaSWeb/etc/tomcat-catalina.policy /etc/cpsagent.web/tomcat-catalina.policy

export PYTHONPATH=/root/ConPaaSWeb/src/:/root/ConPaaSWeb/contrib

# CS - added this line to start Ganglia
/etc/init.d/ganglia-monitor start

/root/ConPaaSWeb/sbin/cpsagent.web -c /root/config.cfg 1>/root/agent.out 2>/root/agent.err &
agent_pid=$!
echo $agent_pid > /root/agent.pid
