#!/bin/bash
# Copyright (C) 2010-2011 Contrail consortium.
# 
# This file is part of ConPaaS, an integrated runtime environment 
# for elastic cloud applications.
# 
# ConPaaS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ConPaaS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ConPaaS.  If not, see <http://www.gnu.org/licenses/>.

#tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
export PYTHONPATH=/root/ConPaaSWeb/src/:/root/ConPaaSWeb/contrib/


/etc/init.d/memcached start
/usr/local/bin/scalarisctl -d -f -s start

/root/ConPaaSWeb/sbin/cpsmanager.web -p 80 -c /root/config.cfg -s $PUBLIC_IP 1>/root/manager.out 2>/root/manager.err &
manager_pid=$!
echo $manager_pid > /root/manager.pid

# CS - added commands to start Ganglia
/etc/init.d/gmetad start
/etc/init.d/ganglia-monitor start

/usr/sbin/nginx -c /var/cache/cpsagent.web/nginx-manager.conf
/etc/init.d/php5-fpm start
