#!/bin/bash
# Copyright (C) 2010-2011 Contrail consortium.
# 
# This file is part of ConPaaS, an integrated runtime environment 
# for elastic cloud applications.
# 
# ConPaaS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ConPaaS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ConPaaS.  If not, see <http://www.gnu.org/licenses/>.

if [ -f /mnt/context.sh ]; then
  . /mnt/context.sh
fi

/sbin/ifconfig eth0 $IP_PUBLIC
/sbin/ip route add default via $IP_GATEWAY
echo "nameserver $NAMESERVER" > /etc/resolv.conf

SOURCE='http://node060.das3.cs.vu.nl/code/'

wget -P /root/ $SOURCE/ConPaaSWeb.tar.gz
wget -P /root/ $SOURCE/manager-start
wget -P /root/ $SOURCE/opennebula-agent-user-data

cat <<EOF > /root/config.cfg
[iaas]
DRIVER = OPENNEBULA

## OPENNEBULA
OPENNEBULA_URL = 
OPENNEBULA_USER = 
OPENNEBULA_PASSWORD =  
OPENNEBULA_IMAGE_ID = 
OPENNEBULA_SIZE_ID = 
OPENNEBULA_NETWORK_ID = 
OPENNEBULA_NETWORK_GATEWAY =  
OPENNEBULA_NETWORK_NAMESERVER = 
OPENNEBULA_AGENT_USERDATA = /root/opennebula-agent-user-data
OPENNEBULA_VIRT_SOLUTION = 
OPENNEBULA_OS_ARCH = 
OPENNEBULA_OS_BOOTLOADER = 
OPENNEBULA_OS_ROOT = 
OPENNEBULA_DISK_TARGET = 
OPENNEBULA_CONTEXT_TARGET = 

[manager]
TYPE = %CONPAAS_SERVICE_TYPE%
BOOTSTRAP = $SOURCE
MEMCACHE_ADDR = 127.0.0.1:11211

ROOT = 
LOG_FILE = %(ROOT)s/var/log/cpsmanager.web.log
ETC = %(ROOT)s/etc/cpsmanager.web/
VAR_TMP = %(ROOT)s/var/tmp/cpsmanager.web/
VAR_CACHE = %(ROOT)s/var/cache/cpsmanager.web/
VAR_RUN = %(ROOT)s/var/run/cpsmanager.web/
CODE_REPO = %(VAR_CACHE)s/code_repo
FE_SERVICE_ID = %CONPAAS_SERVICE_ID%
FE_CREDIT_URL = http://node060.das3.cs.vu.nl/callback/decrementUserCredit.php
FE_TERMINATE_URL = http://node060.das3.cs.vu.nl/callback/terminateService.php
EOF


export PUBLIC_IP=$IP_PUBLIC

##### Configure Ganglia sensor: #####
sed -i -e 's/mcast_join/#mcast_join/' -e 's/bind/#bind/' /etc/ganglia/gmond.conf
sed -i -e 's/host_dmax = 0/host_dmax = 300/' -e 's/send_metadata_interval = 0/send_metadata_interval = 120/' /etc/ganglia/gmond.conf
sed -i -e 's/name = "unspecified"/name = "conpaas"/' /etc/ganglia/gmond.conf
sed -i -e 's/setuid = yes/setuid = no/' /etc/ganglia/gmond.conf

MANAGER_IP="localhost"
HOST_LINE="host = $MANAGER_IP"

echo $HOST_LINE
sed  -i "/udp_send_channel {/ a\ $HOST_LINE" /etc/ganglia/gmond.conf

# configure nginx log
tar -zxf /root/ConPaaSWeb.tar.gz -C /root/
#tar zxf /root/ganglia_web.tar.gz -C root
#cp /root/ganglia_web/nginx_static_log.conf /var/cache/cpsagent.web
cp /root/ConPaaSWeb/misc/ganglia_modules/nginx-manager.conf /var/cache/cpsagent.web
cp /etc/nginx/fastcgi_params /var/cache/cpsagent.web

# configure php-fpm log
cp /root/ConPaaSWeb/misc/ganglia_modules/www.conf /etc/php5/fpm/pool.d/

# create a group such that Ganglia and nginx can access common files 
groupadd conpaas
usermod -a -G conpaas ganglia
usermod -a -G conpaas www-data
chown -R :conpaas /var/cache/cpsagent.web
chmod g+w /var/cache/cpsagent.web/
#mkdir -p /var/cache/cpsagent.web/conf.d

#configure the Ganglia module for nginx monitoring
mkdir -p /etc/ganglia/conf.d
cp /root/ConPaaSWeb/misc/ganglia_modules/modpython.conf /root/ConPaaSWeb/misc/ganglia_modules/*.pyconf /etc/ganglia/conf.d
mkdir -p /usr/lib/ganglia/python_modules
cp /root/ConPaaSWeb/misc/ganglia_modules/nginx_mon.py /usr/lib/ganglia/python_modules
cp /root/ConPaaSWeb/misc/ganglia_modules/php_fpm_mon.py /usr/lib/ganglia/python_modules
####################################


# configure Ganglia gmetad 
sed -i -e 's/my cluster/conpaas/' /etc/ganglia/gmetad.conf

# configure Ganglia web front-end
sed -i -e "s/%SERVER_NAME%/$IP_PUBLIC/" /root/ganglia_web/ganglia_nginx.conf
sed -i -e "s+include /etc/nginx/sites-enabled+#include /etc/nginx/sites-enabled+" /etc/nginx/nginx.conf
#cp /root/ganglia_web/nginx_ganglia.conf /var/cache/cpsagent.web/conf.d/
mkdir -p /var/www
cp -r /root/ConPaaSWeb/contrib/ganglia_frontend/ganglia /var/www/ganglia


chmod 755 /root/manager-start
/root/manager-start

