#!/bin/bash
# Please edit the first three variables in this script. The rest
# should stay as it is, unless you REALLY know what you are doing.

# SOURCE should be set to a URL directory containing files
# agent-start, agent-stop, ec2-agent-user-data, ec2-manager-user-data,
# manager-start and a file ConPaaSWeb.tar.gz containing the entire
# ConPaaS Web hosting service code.
export SOURCE='http://www.whatever.org/code'

# EC2_USER should be set to your EC2 user name. Beware: this is not the
# email address you normally use to login at the AWS management console. 
# An EC2 user name is a long opaque string. It can be found at
# https://aws-portal.amazon.com/gp/aws/developer/account/index.html?action=access-key#account_identifiers
# under the name "Access key ID"
export EC2_USER=''

# EC2_PASSWORD should be set to the corresponding password.
# Again, this is a long opaque string. You can find it next to your
# Access Key ID by clicking "Show Secret Access Key".
export EC2_PASSWORD=''

# EC2_IMAGE_ID should be set to the machine instance ID (AMI ID) that
# should be used. The list of AMIs you have created is available at
# https://console.aws.amazon.com/ec2/home?region=us-east-1#s=Images
EC2_IMAGE_ID=''

# EC2_SIZE_ID represents the type of EC2 instances that should be
# used. T1.micro is for micro-instances, the cheapest (and least
# powerfull) of all.
export EC2_SIZE_ID='t1.micro'

# EC2_SECURITY_GROUP_NAME should be set to the name of your security
# group. The list of your security groups can be found at
# https://console.aws.amazon.com/ec2/home?region=us-east-1#s=SecurityGroups
export EC2_SECURITY_GROUP_NAME=''

# EC2_KEY_NAME should be set to the name of your KeyPair. The list of
# your KeyPairs can be found at
# https://console.aws.amazon.com/ec2/home?region=us-east-1#s=KeyPairs
export EC2_KEY_NAME=''


###############################################
#### Do not edit beyond this point unless  ####
#### you REALLY know what you are doing... ####
#### You have been warned!                 ####
###############################################

export PUBLIC_IP=`/usr/bin/curl http://169.254.169.254/latest/meta-data/public-ipv4`

wget -P /root/ $SOURCE/ConPaaSWeb.tar.gz
wget -P /root/ $SOURCE/manager-start
wget -P /root/ $SOURCE/ec2-agent-user-data
cat <<EOF > /root/config.cfg
[iaas]
DRIVER = EC2
## EC2
EC2_USER = $EC2_USER
EC2_PASSWORD = $EC2_PASSWORD
EC2_IMAGE_ID = $EC2_IMAGE_ID
EC2_SIZE_ID = $EC2_SIZE_ID
EC2_SECURITY_GROUP_NAME = $EC2_SECURITY_GROUP_NAME
EC2_KEY_NAME = $EC2_KEY_NAME
EC2_AGENT_USERDATA = /root/ec2-agent-user-data
[manager]
TYPE = %CONPAAS_SERVICE_TYPE%
BOOTSTRAP = $SOURCE
MEMCACHE_ADDR = 127.0.0.1:11211
ROOT =
LOG_FILE = %(ROOT)s/var/log/cpsmanager.web.log
ETC = %(ROOT)s/etc/cpsmanager.web/
VAR_TMP = %(ROOT)s/var/tmp/cpsmanager.web/
VAR_CACHE = %(ROOT)s/var/cache/cpsmanager.web/
VAR_RUN = %(ROOT)s/var/run/cpsmanager.web/
CODE_REPO = %(VAR_CACHE)s/code_repo
FE_SERVICE_ID = %CONPAAS_SERVICE_ID%
FE_CREDIT_URL = http://testbed.conpaas.eu/callback/decrementUserCredit.php
FE_TERMINATE_URL = http://testbed.conpaas.eu/callback/terminateService.php
EOF
chmod 755 /root/manager-start
/root/manager-start









