#!/bin/bash

ROOT_DIR=/root
CPS_HOME=$ROOT_DIR/ConPaaS

# Source is filled in by the manager
wget -P $ROOT_DIR/ $SOURCE/ConPaaS.tar.gz
tar -zxf $ROOT_DIR/ConPaaS.tar.gz -C $ROOT_DIR/
export PYTHONPATH=$CPS_HOME/src/:$CPS_HOME/contrib/
