#!/bin/bash

# setup and run local agent
for FILE in core-site.xml.tmpl hadoop-env.sh hadoop-metrics.properties.tmpl hadoop-policy.xml mapred-site.xml.tmpl; do
  cp $CPS_HOME/src/conpaas/services/mapreduce/etc/$FILE /etc/hadoop/conf/$FILE
done
cp $CPS_HOME/src/conpaas/services/mapreduce/etc/hue.ini.tmpl /etc/hue/hue.ini.tmpl
rm /etc/hue/hue.ini

$CPS_HOME/sbin/agent/default-cpsagent -c $ROOT_DIR/config.cfg 1>$ROOT_DIR/agent.out 2>$ROOT_DIR/agent.err &
agent_pid=$!
echo $agent_pid > $ROOT_DIR/agent.pid
