#!/bin/bash
mkdir /etc/xos
mkdir /etc/xos/xtreemfs
cp -r $CPS_HOME/src/conpaas/services/xtreemfs/etc/* /etc/xos/xtreemfs/
cp -r $CPS_HOME/src/conpaas/services/xtreemfs/etc/* $ETC/

# Make sure that java will choose ipv4 over ipv6
export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true"

$CPS_HOME/sbin/agent/default-cpsagent -c $ROOT_DIR/config.cfg 1>$ROOT_DIR/agent.out 2>$ROOT_DIR/agent.err &
agent_pid=$!
echo $agent_pid > $ROOT_DIR/agent.pid
