#!/bin/bash
# Copyright (C) 2010-2011 Contrail consortium.
# 
# This file is part of ConPaaS, an integrated runtime environment 
# for elastic cloud applications.
# 
# ConPaaS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ConPaaS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with ConPaaS.  If not, see <http://www.gnu.org/licenses/>.

##
# This script should be run inside a VM to install all dependencies needed by
# the ConPaaSWeb project. The resulting system installation is capable of
# hosting any of the ConPaaSWeb components such as web servers, proxies and
# PHP processes.
# 
# NOTE: This is an interactive script! The user must accept licenses and attend
#       to other prompts.
##


PREFIX=/

function install_deb() {
  sed --in-place 's/main/main contrib non-free/' /etc/apt/sources.list
  apt-get -f -y update
  # install packages
  apt-get -f -y install openssh-server \
        python python-pycurl python-cheetah nginx tomcat6-user memcached \
        make gcc g++ sun-java6-jdk erlang ant libxslt1-dev yaws subversion
  update-rc.d -f memcached remove
  update-rc.d -f nginx remove
  /etc/init.d/memcached stop
  /etc/init.d/nginx stop
  update-rc.d -f yaws remove
  /etc/init.d/yaws stop
  
  # add dotdeb repo for fpm
  echo "deb http://packages.dotdeb.org stable all" >> /etc/apt/sources.list
  wget -O - http://www.dotdeb.org/dotdeb.gpg 2>/dev/null | apt-key add -
  apt-get -f -y update
  apt-get -f -y install php5-fpm php5-curl php5-mcrypt php5-mysql php5-odbc php5-pgsql php5-sqlite php5-sybase php5-xmlrpc php5-xsl php5-adodb php5-memcache
  update-rc.d -f php5-fpm remove
  /etc/init.d/php5-fpm stop
  # remove dotdeb repo
  sed --in-place 's%deb http://packages.dotdeb.org stable all%%' /etc/apt/sources.list
  apt-get -f -y update
  
  echo > /var/log/cpsagent.web.log
  mkdir /etc/cpsagent.web/
  mkdir /var/tmp/cpsagent.web/
  mkdir /var/run/cpsagent.web/
  mkdir /var/cache/cpsagent.web/
  
  echo > /var/log/cpsmanager.web.log
  mkdir /etc/cpsmanager.web/
  mkdir /var/tmp/cpsmanager.web/
  mkdir /var/run/cpsmanager.web/
  mkdir /var/cache/cpsmanager.web/
  
  svn checkout http://scalaris.googlecode.com/svn/trunk/ scalaris-read-only
  cd scalaris-read-only
  ./configure
  make install
  cd ..
  rm -rf scalaris-read-only
	
  # To allow copntextualization to run after snapshotting this instance
  rm /var/lib/ec2-bootstrap/*
}

mkdir -p $PREFIX

install_deb
