#!/bin/bash
# This file creates the final OpenNebula template with all the necessary 
# information to configure and start the BaTS manager.
# This file requires your ONE credentials, as well as your public key and 
# a XtreemFS volume containing the BaTS folder structure.

BASE_INIT_SH=/etc/conpaas/conpaas-taskfarm/init.sh
BASE_TEMPLATE=/etc/conpaas/conpaas-taskfarm/template.one
FINAL_INIT=init.sh
FINAL_TEMPLATE=template.one

if [ "$1" -a "$2" -a "$3" -a "$4" ] 
then
echo "ONE_USER=$1 ONE_PASS=$2 XtreemFS_URL=$3 PUBKEY=$4";
    ONE_USER=$1
    ONE_PASS=$2
    XTFS_URL=$3
    PUBKEY=$4
else
    echo "Usage: $0 ONE_USER ONE_PASS XtreemFS_URL \"PUBKEY\""
    exit 0
fi

sed -e 's|ONE_USER=|ONE_USER='"$ONE_USER"'|' \
    -e 's|ONE_PASSWD=|ONE_PASSWD='"$ONE_PASS"'|' \
    -e 's|FRESH_BATS=|FRESH_BATS='"$XTFS_URL"'|' \
    -e 's|PUBKEY=""|PUBKEY=\"'"$PUBKEY"'\"|'  < $BASE_INIT_SH > $FINAL_INIT

HEXRAW=`xxd -p $FINAL_INIT`
HEX=`echo $HEXRAW | sed 's/ //g'`

sed 's|CONTEXT\ =\ \[|CONTEXT\ =\ \[\
\ \ USERDATA\ =\ \"'"$HEX"'\",|' < $BASE_TEMPLATE > $FINAL_TEMPLATE

rm $FINAL_INIT

echo "Final taskfarm OpenNebula template file is created in $FINAL_TEMPLATE"